version: '3.8'

services:
  mongo:
    image: mongo
    container_name: kstrom_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - kstrom-network

  backend:
    container_name: kstrom_backend
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - MONGO_URI=mongodb://mongo:27017/kstromdb
    depends_on:
      - mongo
    networks:
      - kstrom-network

  frontend:
    container_name: kstrom_frontend
    build: ./frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
    networks:
      - kstrom-network

  nginx:
    image: nginx:alpine
    container_name: kstrom_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - kstrom-network

volumes:
  mongo-data:

networks:
  kstrom-network:
    driver: bridge

