

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - MONGO_URI=mongodb://mongo:27017/kstromdb
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

